### ISSUE TITLE
v2ex 前端页面有变动, theme 和 theme2 都不兼容

### ISSUE THREAD

**Issue by stormeyes** [zdhxiong/v2ex-material-theme2#3]
1. 白色的v2ex logo变回了黑色
2. 首页列表, 列表的帖子状态和帖子标题有部分重合了

希望能修复一下, 非常感谢作者的工作

**Comment by zdhxiong** [comment]
已修复

**Comment by stormeyes** [comment]
@zdhxiong 话题节点貌似也有重叠的问题, 如 https://www.v2ex.com/go/bf4

**Comment by zdhxiong** [comment]
fc4d2f01e456fd2e2cf1bd4ffc1d881d9aa9ca81
